### ISSUE TITLE
AttributeError: 'path' object has no attribute 'makedirs_p'

### ISSUE THREAD

**Issue by soccin** [pickleshare/pickleshare#12]
On MAC OS X (10.10.5)

$ python
Python 2.7.10 (v2.7.10:15c95b7d81dc, May 23 2015, 09:33:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pickleshare import *
>>> db = PickleShareDB('~/testpickleshare')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pickleshare.py", line 63, in __init__
    self.root.makedirs_p()
AttributeError: 'path' object has no attribute 'makedirs_p'

**Comment by takluyver** [comment]
Switched to pathlib, so this is no longer an issue.
