### ISSUE TITLE
pathlib/pathlib2 logic looks suspicious

### ISSUE THREAD

**Issue by mgorny** [pickleshare/pickleshare#26]
The following bit of code, combined with partial dependency on pathlib2 looks weird/suspicious:

```python
try:
    from pathlib import Path
except ImportError:
    # Python 2 backport
    from pathlib2 import Path
```

I'd like to note that — besides the stdlib [pathlib module](https://docs.python.org/3/library/pathlib.html) that is present since Python 3.4, there are two backports out there: [pathlib](https://pypi.python.org/pypi/pathlib) and [pathlib2](https://pypi.python.org/pypi/pathlib2).

The pathlib backport aims to backport the basic pathlib module (from Python 3.4, I think) to older versions of Python in a forward-compatible way. Since it uses the same name as the standard module, it is impossible to use it in Python 3.4+ (the standard module shadows it).

The pathlib2 package is a rolling backport of pathlib from the newest version of Python. It uses a different module name, so that it can be used in newer versions of Python as well (possibly providing newer functions that the pathlib module from the particular version of Python).

That considered, I see two possibilities:
1. you need pathlib with Python 3.4 API — in which case you just `inherit pathlib` unconditionally, and add a dependency on `pathlib` package in Python < 3.4;
2. you need pathlib with newer API — in which case you need to `inherit pathlib2` also in some newer versions of Python, and add appropriate dependency on `pathlib2`.

I think pickleshare falls into the first category. In which case the current code is incorrect since when `pathlib` is installed, then `pathlib2` is never used and the dependency is unnecessary.

**Comment by takluyver** [comment]
My understanding is that the original `pathlib` backport is dead, and `pathlib2` is recommended for all projects that support Python < 3.4.

**Comment by mgorny** [comment]
No, that's not an accurate way of describing it. `pathlib` can not go any further because it is equivalent to `pathlib` in Python 3.4 already, and that's why it's in bugfix-only mode. If upstream were adding new features, those features would not be available for Python 3.4 since there the stdlib takes precedence.

`pathlib2` pretty much goes forward from there, adding new features. If you need the new features, then you need to prefer `pathlib2` over `pathlib` or otherwise e.g. Python 3.4's `pathlib` module will lack them. If you don't, then `pathlib` is no different than `pathlib2`.

**Comment by takluyver** [comment]
The [PyPI page for pathlib](https://pypi.python.org/pypi/pathlib/) says:

> Attention: this backport module isn’t maintained anymore. If you want to report issues or contribute patches, please consider the pathlib2 project instead.

That sounds to me like we should be using pathlib2 as the backport, and people have [filed PRs](https://github.com/jupyter/testpath/pull/8) on other projects I'm aware of switching to pathlib2.

Can you identify any specific failures with what we're doing? If not, let's not fix what isn't broken.

**Comment by mgorny** [comment]
Well, the problem as I see it is that if `pathlib` is installed, it is being used instead of `pathlib2` which in turn renders the dependency wrong. So 'just' inverting the import logic would work for me.

**Comment by takluyver** [comment]
By 'failure', I mean a case where something actually fails. A possibly-unnecessary dependency doesn't necessarily mean there's a failure.

**Comment by mgorny** [comment]
But it works both ways — if pathlib gets used, it also triggers a missing dependency -> QA warning.

**Comment by takluyver** [comment]
Sorry, I don't consider this a bug.
