### ISSUE TITLE
Invite other user

### ISSUE THREAD

**Issue by Carreau** [pickleshare/pickleshare#5]
hey, can you invite me as @Carreau instead of @mbussonn the second one is the one I used at work in France, but is my username in many places also :-)

I guess @minrk an/or @takluyver were invited and can do that also. 

Thanks !

**Comment by vivainio** [comment]
Invite sent

**Comment by Carreau** [comment]
Actually I'm dumb, I could have logged in with my other account and add myself in... Thanks anyway.
